pipeline {
  agent {
    any {
      image 'python:3.10-alpine'
    }

  }
  stages {
    stage('Build') {
      steps {
        bat 'python new.py'
      }
    }

    stage('Test') {
      parallel {
        stage('Test') {
          steps {
            bat 'python3 test_hello.py'
          }
        }

        stage('Test-2') {
          steps {
            bat 'python3 test_world.py'
          }
        }

      }
    }

    stage('error') {
      steps {
        bat 'python3 basic_py_file.py'
      }
    }

  }
}